export class Preferencia{
  constructor(
    public id?: BigInteger,
    public facebook?: string,
    public linkedin?: string,
    public youtube?: string,
    public instagram?: string,
    public whatsapp?: string,
    public twitter?: string,
    public host?: string,
    public driver?: string,
    public username?: string,
    public name?: string,
    public age?: BigInteger,
    public residence?: string,
    public address?: string,
    public rol?: string,
    public about_me?: Text,
    public cv?: string,
    public password?: string,
    public port?: Number,
    public alias?: string,
    public email?: string,
    public direccion?: string,
    public horarios?: string,
    public telefonos?: string,
    public mensaje?: string,
    public restriccion_imagenes?: Number,
    public chat?: string,
    public chat_mostrar?: Number,
    public chat_programar?: Number,
    public dias?: string,
    public created_at?: Date,
    public updated_at?: Date,

  ){}
}
